#!/usr/bin/env python
"""
usage: tropo_delay [-h] [--lineofsight LOS | --statevectors STATEVECTORS]
                   [--area LONG LAT]
                   [--dem DEM | --heightlvs HEIGHTLVS [HEIGHTLVS ...]]
                   [--time TIME] [--model MODEL] [--wrfmodelfiles OUT PLEV]
                   [--wmnetcdf WMNETCDF] [--zref ZREF] [--out OUT]

Calculate tropospheric delay from a weather model

optional arguments:
  -h, --help            show this help message and exit
  --lineofsight LOS, -l LOS
                        GDAL-readable line-of-sight file
  --statevectors STATEVECTORS, -s STATEVECTORS
                        An ISCE XML or shelve file containing state vectors
                        specifying the orbit of the sensor
  --area LONG LAT, -a LONG LAT
                        GDAL-readable longitude and latitude files to specify
                        the region over which to calculate delay. Delay will
                        be calculated at weather model nodes if unspecified
  --dem DEM, -d DEM     DEM file. DEM will be downloaded if not specified
  --heightlvs HEIGHTLVS [HEIGHTLVS ...]
                        Delay will be calculated at each of these heights
                        across all of the specified area
  --time TIME           Fetch weather model data at this (ISO 8601 format)
                        time
  --model MODEL         Weather model to use
  --wmnetcdf WMNETCDF   Weather model netcdf file. Should have q, t, z, lnsp
                        as variables
  --zref ZREF, -z ZREF  Height limit when integrating (meters) (default:
                        15000)
  --out OUT             Output file directory

WRF:
  Arguments for when --model WRF is specified

  --wrfmodelfiles OUT PLEV
                        WRF model files
"""


import argparse
import datetime
import itertools
import importlib
import delay


def read_date(s):
    """Read a date from a string in pseudo-ISO 8601 format."""
    year_formats = (
        '%Y-%m-%d',
        '%Y%m%d',
        '%Y-%m',
        '%Y',  # I don't think anyone would ever want just a year
    )
    time_formats = (
        '',
        'T%H:%M:%S.%f',
        'T%H:%M:%S',
        'T%H%M%S.%f',
        'T%H%M%S',
        'T%H:%M',
        'T%H%M',
        'T%H',
    )
    timezone_formats = (
        '',
        'Z',
        '%z',
    )
    all_formats = map(
        ''.join,
        itertools.product(year_formats, time_formats, timezone_formats))
    date = None
    for date_format in all_formats:
        try:
            date = datetime.datetime.strptime(s, date_format)
        except ValueError:
            continue
    if date is None:
        raise ValueError(
            'Unable to coerce {} to a date. Try %Y-%m-%dT%H:%M:%S.%f%z'.format(s))

    return date


def mangle_model_to_module(model_name):
    """Turn an arbitrary string into a module name.

    Takes as input a model name, which hopefully looks like ERA-I, and
    converts it to a module name, which will look like erai. I doesn't
    always produce a valid module name, but that's not the goal. The
    goal is just to handle common cases.
    """
    return model_name.lower().replace('-', '')


def parse_args():
    """Parse command line arguments using argparse."""
    p = argparse.ArgumentParser(
        description='Calculate tropospheric delay from a weather model')

    # Line of sight
    los = p.add_mutually_exclusive_group()
    los.add_argument(
        '--lineofsight', '-l',
        help='GDAL-readable line-of-sight file',
        metavar='LOS', default=None)
    los.add_argument(
        '--statevectors', '-s', default=None,
        help=('An ISCE XML or shelve file containing state vectors specifying '
              'the orbit of the sensor'))

    # Area
    area = p.add_mutually_exclusive_group()
    area.add_argument(
        '--area', '-a', nargs=2,default = None,
        help=('GDAL-readable longitude and latitude files to specify the '
              'region over which to calculate delay. Delay will be '
              'calculated at weather model nodes if unspecified'),
        metavar=('LAT', 'LONG'))
    area.add_argument(
        '--bounding_box', '-bb', nargs=4,
        help=('Bounding box, given as N W S E'),
        metavar=('N', 'W', 'S', 'E'))
    area.add_argument(
        '--station_file',default = None, type=str,
        help=('File containing a list of stations, with at least '
              'the columns "Lat" and "Lon"'))

    # heights
    heights = p.add_mutually_exclusive_group()
    heights.add_argument(
        '--dem', '-d', default=None,
        help='DEM file. DEM will be downloaded if not specified')
    heights.add_argument(
        '--heightlvs', default=None,
        help=('Delay will be calculated at each of these heights across '
              'all of the specified area'),
        nargs='+', type=float)

    # Weather model
    p.add_argument(
        '--time',
        help='Fetch weather model data at this (ISO 8601 format) time',
        type=read_date, required=True)
    p.add_argument(
        '--model',
        help='Weather model to use',
        default='ERA-5')
    p.add_argument(
        '--pickleFile',
        help='Pickle file to load',
        default=None)

    wrf = p.add_argument_group(
        title='WRF',
        description='Arguments for when --model WRF is specified')
    wrf.add_argument(
        '--wrfmodelfiles', nargs=2,
        help='WRF model files',
        metavar=('OUT', 'PLEV'))

    p.add_argument(
        '--wmnetcdf',
        help=('Weather model netcdf file. Should have q, t, z, lnsp as '
              'variables'))

    # Height max
    p.add_argument(
        '--zref', '-z',
        help=('Height limit when integrating (meters) '
              '(default: %(default)s)'),
        type=int, default=15000)

    p.add_argument(
        '--outformat', help='Output file format; GDAL-compatible for DEM, HDF5 for height levels (default: ENVI)',
        default='ENVI')

    p.add_argument('--out', help='Output file directory', default='.')
    p.add_argument('--model_location', help='Directory where weather model files are stored', default='./weather_files/', dest='wmLoc')

    p.add_argument('--no_parallel', '-p', action='store_true',dest='no_parallel', default = False, help='Do not run operation in parallel? Default False. Recommend only True for verbose (debug) mode')

    p.add_argument('--download_only', action='store_true',dest='download_only', default = False, help='Download weather model only without processing? Default False')

    p.add_argument('--verbose', '-v', action='store_true',dest='verbose', default = False, help='Run in verbose (debug) mode? Default False')

    return p.parse_args(), p

def writeDelays(wetDelay, hydroDelay, time, los, 
                out, outformat, weather_model_name, 
                proj = None, gt = None):
    '''
    Write the delay numpy arrays to files in the format specified 
    '''
    import numpy as np

    # Use zero for nodata
    wetDelay[np.isnan(wetDelay)] = 0.
    hydroDelay[np.isnan(hydroDelay)] = 0.

    # For later
    wetFilename, hydroFilename = \
          util.makeDelayFileNames(time, los, outformat, 
                                  weather_model_name, out)

    writeArrayToRaster(wetDelay, wetFilename, noDataValue = 0., 
                       fmt = outformat, proj = proj, gt = gt)
    writeArrayToRaster(hydroDelay, hydroFilename, noDataValue = 0., 
                       fmt = outformat, proj = proj, gt = gt)



def getTropoDelay():
    """tropo_delay main function.

    We'll parse arguments and call delay.py.
    """
    from utils.util import checkArgs
    import utils.llreader as llr

    args, p = parse_args()

    # Argument checking
    los, lat, lon, heights, weather_model, zref, outformat, \
         time, out, download_only, parallel = checkArgs(args)

    if verbose: 
       print('Starting to run the weather model calculation')
       print('Time type: {}'.format(type(time)))
       print('Time: {}'.format(time.strftime('%Y%m%d')))
       print('Weather model file location: {}'.format(wmLoc))
       print('Parallel is {}'.format(parallel))

    lats, lons, hgts = llr.readLLH(lat, lon, heights)

    if los is None:
        los = Zenith
    else:
        import utils.losreader as losr
        los = losr.infer_los(los, lats, lons, hgts, zref)

    wetDelay, hyrdoDelay = \
       delay.tropo_delay(time, los, lat, lon, hgts, 
                         weather_model, zref, out,
                         parallel=parallel, verbose = verbose, 
                         download_only = download_only)

    writeDelays(wetDelay, hydroDelay, time, los,
                out, outformat, weather_model['name'],
                proj = None, gt = None)

if __name__ == '__main__':
    getTropoDelay()

