version: 2.1

jobs:
  build:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/base:current
        user: root
    steps:
      - checkout

      - run:
          name: Install micromamba
          shell: /bin/bash -xl
          command: |
            apt update --yes && apt upgrade --yes
            apt install --yes --no-install-recommends wget ca-certificates git

            # Put micromamba's shell init script into a profile.d file instead
            # of .bashrc, in order to activate it even in CircleCI's
            # non-interactive terminals.
            mv ${HOME}/.bashrc ${HOME}/.bashrc.tmp &> /dev/null
            # From https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html#automatic-install
            curl -L micro.mamba.pm/install.sh | "${SHELL}"
            mv ${HOME}/.bashrc /etc/profile.d/mamba-raider-circleci.sh
            mv ${HOME}/.bashrc.tmp ${HOME}/.bashrc &> /dev/null

      - run:
          name: Create RAiDER environment
          no_output_timeout: 60m
          shell: /bin/bash -xl
          command: |
            PYTHON_VERSION="<< parameters.python-version >>"
            sed -i "/python>=/c\ - python=${PYTHON_VERSION}" environment.yml
            # Create RAiDER enivronment
            micromamba env create --yes -f environment.yml
            # Activate the RAiDER env for the rest of this script's steps
            echo "micromamba activate RAiDER" >> /etc/profile.d/mamba-raider-circleci.sh

      - run:
          name: Install RAiDER and check environment
          shell: /bin/bash -xl
          command: |
            python -m pip install --no-deps .

            python -c "import RAiDER; from RAiDER.delay import tropo_delay"
            python -c "import RAiDER; from RAiDER.interpolator import interp_along_axis"

            python --version
            python -c "import numpy; print(numpy.__version__)"
            python -c "import pyproj; print(pyproj.__version__)"

      - run:
          name: Set up data stores
          shell: /bin/bash -xl
          command: |
            python -c 'from RAiDER.models.credentials import setup_from_env; setup_from_env()'

      - run:
          name: Run unit tests
          shell: /bin/bash -xl
          command: |
            python -m pip install pytest-cov
            COV_OPTIONS=`python -c "import importlib.util; print(*(' --cov='+p for p in importlib.util.find_spec('RAiDER').submodule_search_locations))"`
            pytest -m "not long" test/ ${COV_OPTIONS} --cov-report=

      - run:
          name: Report coverage
          shell: /bin/bash -xl
          command: |
            # Only run the coverage test on the latest supported version (3.12)
            PYTHON_VERSION="<< parameters.python-version >>"
            if [ "${PYTHON_VERSION}" == "3.12" ]; then
              python -m pip install coveralls
              python .circleci/fix_coverage_paths.py .coverage ${PWD}/tools/RAiDER/
              coverage report -mi --show-missing --data-file=.coverage
              coveralls --verbose
            fi

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11", "3.12"]
